# Generated by Django 5.1.5 on 2025-02-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_alter_game_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, default='covers/default.jpg', upload_to='covers/'),
        ),
    ]
