# Generated by Django 5.1.5 on 2025-01-31 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('games', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('status', models.IntegerField(choices=[(1, 'Initiated'), (2, 'Confirmed'), (3, 'Paid'), (-1, 'Cancelled')], default=1)),
                ('created_at', models.DateTimeField()),
                ('updated_at', models.DateTimeField()),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('games', models.ManyToManyField(to='games.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
